---
- hosts: all
  
  tasks:

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
    
  - name: Autoremove unused packages
    command: apt -y autoremove
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"
