---
- hosts: all
  
  tasks:

  - name: Update APT package cache
    become: true
    apt: update_cache=yes cache_valid_time=600

  - name: Upgrade APT to the latest packages
    become: true
    apt: upgrade=dist
    register: apt_result
    
  - name: Autoremove unused packages
    become: true
    command: apt-get -y autoremove
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"

  - name: Purge residual kernel packages
    become: true
    shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"
